# model
model_name_or_path: ''
# data
dataset_name: 'own_medical'
refresh: false
data_tag: '200_600A_200_updated_prompts'
train_on_inputs: false
data_max_length: 1024
domain: 'legal'
# training
# trainer
tag: 'lomo'
output_dir: ''
overwrite_output_dir: true
deepspeed: 'config/ds_config.json'
do_train: true
do_eval: false
evaluation_strategy: 'epoch'
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 0.03
weight_decay: 0
num_train_epochs: 5
lr_scheduler_type: 'linear'
warmup: 0.1
clip_grad_norm: 1.0
save_strategy: 'epoch'
save_total_limit: 5
seed: 42
llama_type: '7b'
general_importance_dir: ''
#bf16: true
remove_unused_columns: false
load_best_model_at_end: false
metric_for_best_model: 'acc'
group_by_length: false
#report_to: 'wandb'
dataloader_pin_memory: false
gradient_checkpointing: true
predict_with_generate: true